# Generated by Django 4.2.7 on 2025-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='client_metrics',
            field=models.JSONField(default=dict),
        ),
    ]
