# Generated by Django 4.2.7 on 2025-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_jirafile_original_filename_alter_jirafile_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='actionable_insights',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='theme_visualization',
            field=models.JSONField(default=list),
        ),
    ]
