# Generated by Django 4.2.7 on 2025-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_analysisresult_actionable_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirafile',
            name='analysis_date',
            field=models.DateField(blank=True, help_text='Date selected for analysis filtering and context', null=True),
        ),
    ]
