# Generated by Django 4.2.7 on 2025-06-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_surveyfile_surveyresponse_surveyanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='rag_indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='rag_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyanalysis',
            name='rag_indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyanalysis',
            name='rag_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
